### ISSUE TITLE
Drop contextlib2 requirement?

### ISSUE THREAD

**Issue by opoplawski** [keleshev/schema#282]
Is there any reason for the contextlib2 requirement?  Is the standard python contextlib not sufficient?  It seems like the needed functionality was added in python 3.3, which is long EOL, and 0.5.5 was released in 2017.

**Comment by skorokithakis** [comment]
Hmm, if it works, I suppose it's not necessary, it's a relic.

**Comment by dvzrv** [comment]
Hi! :wave: 

On Arch Linux we would like to drop the python-contextlib2 package (due to above mentioned reasons).
This project is the last dependent of contextlib2.

https://github.com/keleshev/schema/pull/291 already appears to remove this dependency for Python versions < 3.3.

Can it please be merged? :)

**Comment by skorokithakis** [comment]
Done, thanks!
