### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by marc2982** [keleshev/schema#59]
There hasn't been a release since last April and I would like to use the new defaulting functionality. Would you mind cutting a new release?

Thanks!

**Comment by perriv** [comment]
Same here. Just wrote code based off of the master branch. Was wondering why I was getting:

`TypeError: __init__() got an unexpected keyword argument 'default'`.

Thanks @marc2982 , I am finding schema to be very expressive for what I need to do.

**Comment by drgarcia1986** [comment]
Same here :sob: 
```python
>>> from schema import Schema, Optional
>>> s = Schema({Optional('foo', default=1)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'default'
__init__() got an unexpected keyword argument 'default'
```

**Comment by sjakobi** [comment]
@skorokithakis: How's it looking?

I'd propose that you delay any API decisions and merge #84 and #85.

Then adjust the install instructions in the README for the new version number and get it out of the door! :grinning:

Issues like #80 or #83 don't seem to be problematic in the wild, so I'd argue that they might just as well be delayed for the next release.

**Comment by sjakobi** [comment]
Or are there other things that absolutely need to get into the next release?
Anything I can assist with?

**Comment by skorokithakis** [comment]
I'm kinda having trouble replying to all your improvements :P I don't think there are any API decisions to be made, I'm sure a 0.3.2 release could easily be made from the current fixes. I'm just waiting for a fix in #85 to merge that, and then we can release. In my projects, I release minor revisions even for a single bugfix, since they're pretty cheap (although it depends on how active the project is, too).

**Comment by sjakobi** [comment]
#85 is ready BTW.

**Comment by skorokithakis** [comment]
Merged, thank you!

**Comment by skorokithakis** [comment]
@keleshev, ready for a new release when you are.

**Comment by jab** [comment]
Hi maintainers, if something is holding up a new stable release, can you release master to PyPI as a beta release in the meantime, as it has some nice fixes? Let us know if there's anything community can do to help.

**Comment by skorokithakis** [comment]
Only @keleshev can do that, unfortunately, or I would have. Paging @keleshev.

**Comment by keleshev** [comment]
@skorokithakis what's you PyPI username?

**Comment by skorokithakis** [comment]
It's "stochastic".

**Comment by keleshev** [comment]
@skorokithakis added you as maintainer.

My feedback on the current release: Since last release several top-level names were introduced (like `MARKER` and priorities), I think they are not part of public API, thus we need to either prefix them with underscore, or create an `__all__` variable that excludes them.

After that you can release the new version.

Please ping me next time you release so I can review the changes. Keep it backwards-compatible. And thanks for helping out with the project.

**Comment by kosz85** [comment]
Before releasing I suggest to review and merge also pull request #65

**Comment by jab** [comment]
Now that #65 is closed, is this a good time to release 0.3.2?

**Comment by jab** [comment]
Hey @skorokithakis and @keleshev, anything else holding up the next release, possibly that anyone else can help with?

**Comment by keleshev** [comment]
We need #97 or something like it before releasing.

**Comment by skorokithakis** [comment]
@keleshev, do you want to do the honours for this one? I'm not sure how the release process goes, do you just change the version to remove dev0, upload and commit, or do you bump the version to the next minor dev0 and release without committing 0.3.2?

**Comment by keleshev** [comment]
* Change version to 0.4.0; commit.
* `python setup.py sdist upload`.
* Test `pip install` in a virtualenv; if all works:
    * Change version to `0.4.0-alpha` (semver); commit.
    * Push to GitHub.

This release adds features that's why the version bump to `0.4.0`. Somehow non-semver version `0.3.2.dev0` slipped into source, supposed to be `0.3.2-dev0` or `0.3.2-dev` or, I prefer `0.3.2-alpha`.

**Comment by jab** [comment]
@keleshev wrote:

> Somehow non-semver version 0.3.2.dev0 slipped into source

Please review https://github.com/keleshev/schema/pull/90#issuecomment-144228504

**Comment by skorokithakis** [comment]
By the way, shouldn't the next version in master be `0.4.0-alpha`, since `0.4.0` was just released?

**Comment by keleshev** [comment]
@skorokithakis ah, yeah, good catch.
